# 作業
### 用 digits (3個數字即可 , dataset.load_digits(n_class=3)) 資料嘗試跑 PCA


In [1]:
from sklearn import datasets

digits = datasets.load_digits(n_class=3)
X = digits.data
y = digits.target

In [2]:
X[536]

array([ 0.,  0.,  6., 16., 13., 11.,  1.,  0.,  0.,  0., 16., 15., 12.,
       16.,  1.,  0.,  0.,  3., 16.,  7.,  0., 13.,  6.,  0.,  0.,  4.,
       16.,  0.,  0., 10.,  8.,  0.,  0.,  8., 16.,  0.,  0., 14.,  6.,
        0.,  0.,  5., 16.,  7.,  9., 16.,  5.,  0.,  0.,  1., 15., 16.,
       16., 16.,  1.,  0.,  0.,  0.,  6., 16., 14.,  6.,  0.,  0.])

載入 相關套件 並 執行 PCA 實驗 ...

In [3]:
print(len(X))     #537筆資料
print(len(X[1]))  #64個attributes
print(X.shape[1] / 2)
print(y)

537
64
32.0
[0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0 1 2 1 1 1 1 0 1 2 2
 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0 1 2 1 1 1 1 0 1
 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0 1 2 1 1 1 1
 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0 1 2 1 1
 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0 1 2
 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2 0 0
 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2
 0 0 1 2 1 1 1 1 0 1 2 2 2 0 1 2 0 1 2 0 1 2 0 0 1 1 2 2 0 1 2 1 0 2 2 0 0
 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 0 1 2 1 0 2 2 0 0
 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0 2 2
 0 0 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2 1 0
 2 2 0 0 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0 1 2
 1 0 2 2 0 0 1 2 1 1 1 1 0 1 2 2 2 0 0 1 2 0 1 2 0 1 2 0 0 1 1 0 0 2 2 2 0
 1 2 1 0 2 0 

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


from sklearn import decomposition
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score

np.random.seed(5)
%matplotlib inline

In [5]:
n_clusters = 3
clusterer = KMeans(n_clusters=n_clusters, random_state=10)
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([0, 1, 1, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1,
       1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2,
       1, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2,
       0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2,

In [6]:
accuracy_score(y, cluster_labels)
print('原本的準確率',accuracy_score(y, cluster_labels))

原本的準確率 0.9217877094972067


In [7]:
#嘗試降到一半
pca = decomposition.PCA(n_components=int(X.shape[1] / 2) )

In [8]:
pca.fit(X)
X_pca = pca.transform(X)

len(X_pca[1])

32

In [9]:
n_clusters = 3
clusterer = KMeans(n_clusters=n_clusters, random_state=10)
cluster_labels = clusterer.fit_predict(X_pca)
cluster_labels

array([0, 1, 1, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1,
       1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0,
       2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2,
       1, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2,
       0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2,

In [10]:
print('降一半的準確率',accuracy_score(y, cluster_labels))

降一半的準確率 0.9217877094972067


In [11]:
#嘗試再降到一半
pca = decomposition.PCA(n_components=int(X.shape[1] / 4) )
pca.fit(X)
X_pca = pca.transform(X)

len(X_pca[1])

16

In [12]:
n_clusters = 3
clusterer = KMeans(n_clusters=n_clusters, random_state=10)
cluster_labels = clusterer.fit_predict(X_pca)
cluster_labels

array([2, 1, 1, 2, 1, 0, 2, 1, 0, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1,
       2, 1, 1, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2, 1,
       0, 2, 1, 0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 2, 0, 0, 2, 2,
       1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 0, 1, 1, 1,
       1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 1, 1, 2, 2,
       0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0,
       1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0,
       0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       2, 1, 0, 2, 1, 0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 2, 0, 0,
       2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 1,
       0, 2, 2, 1, 1, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 0, 0, 1,
       1, 1, 1, 2, 1, 0, 1, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0,
       0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0,

In [13]:
print('降四分之一的準確率',accuracy_score(y, cluster_labels))

降四分之一的準確率 0.2905027932960894
