## 作業

1. 試著調整 RandomForestClassifier(...) 中的參數，並觀察是否會改變結果？
2. 改用其他資料集 (boston, wine)，並與回歸模型與決策樹的結果進行比較

In [16]:
from sklearn import datasets, metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [17]:
# 讀取鳶尾花資料集
iris = datasets.load_iris()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=4)

# 建立模型
clf = RandomForestClassifier(
    n_estimators=20,
    criterion="gini",
    max_features="auto", #如何選取 features
     max_depth=10,
    min_samples_split=2,
    min_samples_leaf=1
    )

# 訓練模型
clf.fit(x_train, y_train)

# 預測測試集
y_pred = clf.predict(x_test)

In [3]:
acc = metrics.accuracy_score(y_test, y_pred)
print("Acuuracy: ", acc)

Acuuracy:  0.9473684210526315


In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print("Feature importance: ", clf.feature_importances_)

Feature importance:  [0.13823068 0.02088999 0.38459159 0.45628773]


# DataSet Boston

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [7]:
#取得資料
boston = datasets.load_boston()
#轉成ponda
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
#X = boston.data[:]
X = boston.data[:]
print("Data shape: ", X.shape) # 可以看見有 442 筆資料與我們取出的其中一個 feature
print(X)

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston_df, boston.target, test_size=0.2, random_state=4)

Data shape:  (506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


## LinearRegression

In [8]:
from sklearn import datasets, metrics

# 如果是分類問題，請使用 DecisionTreeClassifier，若為回歸問題，請使用 DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [9]:
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [10]:
# 預測值與實際值的差距，使用 MSE
print("LinearRegression Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

LinearRegression Mean squared error: 25.41


## Decision Tree

In [11]:
# 建立模型
dtr = DecisionTreeRegressor()

# 訓練模型
dtr.fit(x_train, y_train)

# 預測測試集
y_pred = dtr.predict(x_test)

In [12]:
# 預測值與實際值的差距，使用 MSE
print("Decision Tree Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Decision Tree Mean squared error: 23.90


## Randomforest

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [14]:
# 建立模型
rfc = RandomForestRegressor()

# 訓練模型
rfc.fit(x_train, y_train)

# 預測測試集
y_pred = rfc.predict(x_test)

In [15]:
# 預測值與實際值的差距，使用 MSE
print("Random forest Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Random forest Mean squared error: 14.43
