## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [2]:
#取得資料
boston = datasets.load_boston()

#轉成ponda
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
#查看資料型態
print(boston_df.info())
boston_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB
None


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [3]:
#查看目標型態
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [4]:
#X = boston.data[:]
X = boston.data[:]
print("Data shape: ", X.shape) # 可以看見有 442 筆資料與我們取出的其中一個 feature
print(X)

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston_df, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

Data shape:  (506, 13)
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [5]:
# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Coefficients:  [-1.14743504e-01  4.70875035e-02  8.70282354e-03  3.23818824e+00
 -1.67240567e+01  3.87662996e+00 -1.08218769e-02 -1.54144627e+00
  2.92604151e-01 -1.33989537e-02 -9.07306805e-01  8.91271054e-03
 -4.58747039e-01]
Mean squared error: 25.41


##Lasso

In [6]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=0.001)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

In [7]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-1.14561044e-01,  4.71145361e-02,  7.26871520e-03,  3.21453657e+00,
       -1.63950307e+01,  3.87760778e+00, -1.10705423e-02, -1.53616665e+00,
        2.91783958e-01, -1.34201661e-02, -9.03969148e-01,  8.92800709e-03,
       -4.59277240e-01])

In [8]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41


###找出最好的alpha

In [9]:
# 初始化一个Ridge Cross-Validation Regression
clf = linear_model.LassoCV(alphas=None, copy_X=True, cv=None, eps=0.0001, fit_intercept=True,
    max_iter=10000, n_alphas=100, n_jobs=1, normalize=False, positive=False,
    precompute='auto', random_state=None, selection='cyclic', tol=0.000001,
    verbose=False)

# 训练模型
clf.fit(x_train, y_train)

print ('alpha的數值 : ', clf.alpha_)
print ('參數的數值：', clf.coef_)

alpha的數值 :  0.07667290492353691
參數的數值： [-0.10493319  0.0487776  -0.05010061  1.56388946 -0.          3.87189435
 -0.02216559 -1.24963822  0.25655752 -0.01497302 -0.74312332  0.00972675
 -0.49340858]


In [10]:
# 將測試資料丟進模型得到預測結果
y_pred = clf.predict(x_test)
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 26.44


##Ridge

In [11]:
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [12]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[-1.11085562e-01  4.79127892e-02 -2.36686153e-02  2.96582333e+00
 -9.35915972e+00  3.92379527e+00 -1.73228057e-02 -1.43323726e+00
  2.74489395e-01 -1.38858412e-02 -8.31911824e-01  9.25837299e-03
 -4.67523596e-01]


In [13]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41


In [14]:
# 初始化一个Ridge Cross-Validation Regression
clf = linear_model.RidgeCV(fit_intercept=True)

# 训练模型
clf.fit(x_train, y_train)
# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

print ('alpha的數值 : ', clf.alpha_)
print ('參數的數值：', clf.coef_)

alpha的數值 :  0.1
參數的數值： [-1.14125970e-01  4.72144096e-02  3.30466950e-03  3.20052271e+00
 -1.55057123e+01  3.88649056e+00 -1.19216295e-02 -1.52356227e+00
  2.89503886e-01 -1.34748452e-02 -8.94652812e-01  8.97005058e-03
 -4.60013402e-01]


In [15]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(clf.coef_)

[-1.14125970e-01  4.72144096e-02  3.30466950e-03  3.20052271e+00
 -1.55057123e+01  3.88649056e+00 -1.19216295e-02 -1.52356227e+00
  2.89503886e-01 -1.34748452e-02 -8.94652812e-01  8.97005058e-03
 -4.60013402e-01]


In [16]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.41
