In [20]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [21]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [22]:
#Variable initialization
epoch = 5 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set ，input 有三個參數
hiddenlayer_neurons = 3 #number of hidden layers neurons，一個hidden layer 中有三個參數
output_neurons = 1 #number of neurons at output layer

In [23]:
#weight and bias initialization
#input + weight 
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) )  
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [24]:
wh

array([[0.43936148, 0.84081119, 0.52461684],
       [0.21093528, 0.39390181, 0.85422037],
       [0.30286471, 0.89749176, 0.61191253],
       [0.56516605, 0.30504651, 0.11543511]])

In [25]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [26]:
np.dot(X,wh)

array([[0.7422262 , 1.73830295, 1.13652937],
       [1.30739225, 2.04334946, 1.25196448],
       [0.77610133, 0.69894832, 0.96965548]])

# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [30]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh)  #矩陣相乘
    
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 

    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.78930508]
 [0.80478988]
 [0.77544136]]
wout,bout of Backpropagation:
[[0.69723987]
 [0.52518956]
 [0.27428728]],
[[0.17045]]
